name: baseball
author: rain1208
main: rain1208\baseball\Main
api: 3.0.0
version: 1.0.0

commands:
  bat:
    description: "batを配布します"
  clearball:
    description: "ボールを消す"
  multiply:
    description: "飛距離を変更"