main: rain1208\code\Main
name: code
author: rain1208
api: 3.0.0
version: 2.0.0
depend:
  - EconomyAPI

commands:
  code:
    description: "アイテムを受け取ります"
  addcode:
    description: "コードを追加します"
    permission: op